spring:
  profiles:
    active: local # 기본 환경 선택

# local 환경
---
spring:
  profiles: local
  datasource:
    url: jdbc:mysql://localhost:3306/spring?serverTimezone=UTC&characterEncoding=UTF-8
    username: springboot
    password: spring
    initialization-mode: always
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop